# Generated by Django 5.0.1 on 2025-12-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Cap Braco', max_length=200)),
                ('hero_subtitle', models.TextField(default="Let's work together.")),
                ('logo_text', models.CharField(default='CAPBRACO', max_length=50)),
                ('fire_effect_enabled', models.BooleanField(default=True)),
                ('fire_effect_duration', models.IntegerField(default=8000, help_text='Duration in milliseconds')),
                ('about_title', models.CharField(default='About Me', max_length=200)),
                ('about_content', models.TextField(blank=True)),
                ('resume_file', models.FileField(blank=True, help_text='PDF resume', upload_to='documents/')),
                ('email', models.EmailField(default='dev@capbraco.com', max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('site_title', models.CharField(default='CapBraco', max_length=100)),
                ('site_description', models.TextField(default='Portfolio & Development Hub')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
