# Generated by Django 5.0.1 on 2025-12-21 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('flagship', 'Flagship Project'), ('web', 'Web Development'), ('3d', '3D Modeling & Animation'), ('experiment', 'Experiment')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('featured', 'Featured')], default='draft', max_length=20)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', models.TextField()),
                ('challenge', models.TextField(blank=True, help_text='What was the problem?')),
                ('solution', models.TextField(blank=True, help_text='How did you solve it?')),
                ('outcome', models.TextField(blank=True, help_text='What was the result?')),
                ('hero_image', models.ImageField(upload_to='projects/heroes/')),
                ('demo_video', models.URLField(blank=True)),
                ('tech_stack', models.JSONField(default=list, help_text='List of technologies used')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-display_order', '-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='portfolio_p_publish_058fc2_idx'), models.Index(fields=['status', '-display_order'], name='portfolio_p_status_23d5a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
